name: rp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - scikit-learn
  - joblib
  - pandas
  - scipy
  - conda-pack
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cpu
      - tensorflow-cpu
      - torch
      - nflows
      - fastapi
      - uvicorn[standard]
      - pydantic
      - httpx
      - python-multipart